import type { Metadata } from 'next'
import './globals.css'
import Navigator from './components/UI/Navigator'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=' overflow-y-hidden h-full'>
      <body className='h-full'>
        <Navigator/>
        {children}
      </body>
    </html>
  )
}
